function [ idx ] = CountrySort( country )
%UNTITLED4 Summary of this function goes here
%   Detailed explanation goes here

countryCodes = {
    'ISL', 'UKR', 'SVN', 'MEX', 'BGD', ...
    'ISR', 'NOR', 'PHL', 'MYS', 'CHN', ...
    'SYC', 'GHA', 'MAR', 'USA', 'TZA', ...
    'JOR', 'ARM', 'BWA', 'MDA', 'MUS', ...
    'GRC', 'LUX', 'LTU', 'HKG', 'CZE', ...
    'SRB', 'DNK', 'BMU', 'PRT', 'KHM', ...
    'ROM', 'OMN', 'KOR', 'IRL', 'TWN', ...
    'BGR', 'MMR', 'AUT', 'POL', 'LBN', ...
    'BHR', 'DOM', 'THA', 'ITA', 'CAN', ...
    'SLV', 'GBR', 'CHE', 'EGY', 'ESP', ...
    'GIB', 'NPL', 'CYM', 'BEL', 'MKD', ...
    'TUN', 'DZA', 'SVK', 'KEN', 'SWE', ...
    'DEU', 'NZL', 'CMR', 'BRA', 'ARE', ...
    'FIN', 'PER', 'CYP', 'CHL', 'CRI', ...
    'NLD', 'ARG', 'NGA', 'NIC', 'SAU', ...
    'MLT', 'HRV', 'BHS', 'AZE', 'SGP', ...
    'SOM', 'FRA', 'TUR', 'PAN', 'ECU', ...
    'BLR', 'COL', 'UGA', 'JPN', 'IND', ...
    'LVA', 'IDN', 'RUS', 'GTM', 'HUN', ...
    'AUS', 'MAF', 'EST', 'PAK'};

    [~,idx] = ind2sub(size(countryCodes), strmatch(country, countryCodes, 'exact'));

end

